### ISSUE TITLE
Is it Java 1.8 compatible like the Elastic Search Java Client?

### ISSUE THREAD

**Issue by chrisco484** [spinscale/elasticsearch-rest-client-samples#2]
Given that the new Elastic Search Java Client is designed to require only 1.8 are these examples also compatible with 1.8?

When trying to build I got a message that looks like it requires Java 17:

> Starting a Gradle Daemon (subsequent builds will be faster)
> > Task :compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileJava'.
> > invalid source release: 17

It seems like it wants to be compiled with Java 17 - is there anyway to limit it to Java 1.8?

**Comment by chrisco484** [comment]
Actually, given that Elastic Search server 8.x requires Java 17 or later maybe that mandates this samples project using Java 17...

Although if the server is running inside a container wouldn't that mean that Java 17 would need to run inside the container but would not be required to run the Elastic client 8.x client samples outside the container that just use the new light weight Elastic client 8.x to connect to the Dockerized elastic server?

**Comment by spinscale** [comment]
You are right with your last comment. While this project has been set to java 17, the client itself also works on java 8 projects - completely independent from the Java version Elasticsearch is running on.

Hope that helps, otherwise, feel free to ask for further details.

**Comment by chrisco484** [comment]
I ended up going "brute force" in the end: I installed Elastic search and Kibana on "bare metal" via a spare HP server and then made a separate project with some of the Java client examples.

My job was made harder by attempting to run the Java client on a separate host to the elastic search server.

Tricks for rookies:

- Elastic search has an embedded JDK - time spent downloading and installing the latest OpenJDK and fiddling with the lovely 'alternatives' on my server was wasted ;)
- Elastic search service is set up by default to NOT allow connections from anything but localhost. So you need to uncomment:
network.host: x.x.x.x
    and set the IP to your elastic search server's IP address.
    Then save and restart elastic search e.g. systemctl restart elasticsearch
- Grab the http_ca.crt file from the elastic search server: /etc/elasticsearch/certs and store it on your dev PC running the elastic Java client app and use it directly (a bit easier than setting up a keystore or a proper CA trust - but all options are well explained in the elastic doc pages)

 Here's a sample client set up that got me working in the end:
 
```
RestClient restClient;
ElasticsearchTransport transport;
ElasticsearchClient client;

	// Credentials provider
	final CredentialsProvider credentialsProvider =
		new BasicCredentialsProvider();
	credentialsProvider.setCredentials(AuthScope.ANY,
		new UsernamePasswordCredentials("elastic", "YOUR_ELASTIC_USER_PASSWORD")); 
		// Hint: for dev environment you can simply use the password auto generated during elastic installation

	// Certificate for SSL/TLS context
	Path caCertificatePath = Paths.get("C:\\PATH_TO_YOUR_CERTS\\http_ca.crt");
	CertificateFactory factory =
		CertificateFactory.getInstance("X.509");
	Certificate trustedCa;
	try (InputStream is = Files.newInputStream(caCertificatePath)) {
		trustedCa = factory.generateCertificate(is);
	}
	KeyStore trustStore = KeyStore.getInstance("pkcs12");
	trustStore.load(null, null);
	trustStore.setCertificateEntry("ca", trustedCa);
	SSLContextBuilder sslContextBuilder = SSLContexts.custom()
		.loadTrustMaterial(trustStore, null);
	final SSLContext sslContext = sslContextBuilder.build();


	restClient = RestClient.builder(
			new HttpHost("YOUR_ELASTIC_SEARCH_HOSTNAME", 9200, "https"))
		.setHttpClientConfigCallback(new RestClientBuilder.HttpClientConfigCallback() {
			@Override
			public HttpAsyncClientBuilder customizeHttpClient(
				HttpAsyncClientBuilder httpClientBuilder) {
				return httpClientBuilder.setSSLContext(sslContext).setDefaultCredentialsProvider(credentialsProvider);
			}
		}).build();


	// Create the transport with a Jackson mapper
	transport = new RestClientTransport(
		restClient, new JacksonJsonpMapper());

	// And create the API client
	client = new ElasticsearchClient(transport);

```
